### ISSUE TITLE
Advise on discovery of modification from peptides

### ISSUE THREAD

**Issue by BenSamy2020** [SimpleNumber/aa_stat#10]
Greetings @levitsky,

I am intending to search some immunopeptidomics datasets using MSFragger nonspecific-HLA workflow. Performing OpenSearch using non-specific enzyme and inputting it into AA_Stats would not be a viable option. 

By any chance could you advise me on how to discovery modifications using AA_Stat from immunopeptidomics data searches that can subsequently be used to set into MSFragger workflow?

Regards,
Ben

**Comment by levitsky** [comment]
Hi Ben,

I don't have any specific answers, but if you want to try making it work with open search, maybe you can try reducing the database by excluding the bulk of irrelevant proteins? Another possibility is reducing the search space by using a more narrow window or maybe a pre-selected list of mass shifts, using the [mass offsets](https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#mass_offsets) parameter with "closed" search.

Perhaps you can also try some other "open modification" search engines, but I don't really have any experience with that.

Best regards,
Lev

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

Thank you for your prompt reply. I will follow-up with this thread from email. Will be emailing you soon.

Regards,
Ben
