### ISSUE TITLE
Error: fix_mod

### ISSUE THREAD

**Issue by BenSamy2020** [SimpleNumber/aa_stat#11]
Greetings @levitsky,

Currently, I am trying to perform AA_Stat analysis using Open Search results. This Open Search was performed as per our discussion via email. The error is as following:

C:\Users\parth>AA_stat --dir D:\MSFragger_Temp\Immunopeptidomics\CRC_Immunopeptidomics\MSFragger_OpenSearch_1_Output\AA_Stat\Output --pepxml D:\MSFragger_Temp\Immunopeptidomics\CRC_Immunopeptidomics\MSFragger_OpenSearch_1_Output\AA_Stat\pepXML --mzml D:\MSFragger_Temp\Immunopeptidomics\CRC_Immunopeptidomics\MSFragger_OpenSearch_1_Output\AA_Stat\mzML --verbosity 3
    INFO: [23:46:52] Starting...
   DEBUG: [23:46:52] Received pepxml list: ['D:\\MSFragger_Temp\\Immunopeptidomics\\CRC_Immunopeptidomics\\MSFragger_OpenSearch_1_Output\\AA_Stat\\pepXML']
   DEBUG: [23:46:52] Found 0 files for glob *.pepXML
   DEBUG: [23:46:52] Found 0 files for glob *.pep.xml
   DEBUG: [23:46:52] Final pepxml list: []
   DEBUG: [23:46:52] Received mzml list: ['D:\\MSFragger_Temp\\Immunopeptidomics\\CRC_Immunopeptidomics\\MSFragger_OpenSearch_1_Output\\AA_Stat\\mzML']
   DEBUG: [23:46:52] Found 0 files for glob *.mzML
   DEBUG: [23:46:52] Final mzml list: []
   DEBUG: [23:46:52] Received args: Namespace(params=None, dir='D:\\MSFragger_Temp\\Immunopeptidomics\\CRC_Immunopeptidomics\\MSFragger_OpenSearch_1_Output\\AA_Stat\\Output', verbosity=3, mgf=None, mzml=[], pepxml=[], csv=None)
    INFO: [23:46:52] Using default parameters for AA_stat.
   DEBUG: [23:46:52] defaultdict(None, {'decoy_prefix': '', 'decoy_prefix_list': ['rev_', 'DECOY_'], 'FDR': 0.02, 'labels': ['M', 'D', 'Q', 'C', 'L', 'H', 'S', 'R', 'A', 'W', 'Y', 'P', 'F', 'V', 'N', 'T', 'E', 'G', 'I', 'K'], 'rule': 'trypsin', 'csv_delimiter': ',', 'proteins_delimeter': ';', 'proteins_column': 'protein', 'peptides_column': 'peptide', 'mass_shifts_column': 'massdiff', 'score_column': 'expect', 'measured_mass_column': 'precursor_neutral_mass', 'calculated_mass_column': 'calc_neutral_pep_mass', 'rt_column': 'retention_time_sec', 'next_aa_column': 'peptide_next_aa', 'prev_aa_column': 'peptide_prev_aa', 'spectrum_column': 'spectrum', 'charge_column': 'assumed_charge', 'mods_column': 'modifications', 'score_ascending': True, 'bin_width': 0.001, 'so_range': (-500.0, 500.0), 'walking_window': 0.012, 'FDR_correction': True, 'processes': 0, 'zero_window': 0.05, 'prec_acc': 0.01, 'zero bin tolerance': 0.05, 'zero min intensity': 0.05, 'min_peptides_for_mass_calibration': 100, 'specific_mass_shift_flag': False, 'specific_window': [15.975, 16.005], 'figsize': (9.0, 3.5), 'calibration': 'gauss_frequency', 'artefact_thresh': 0.5, 'html_truncate': 80, 'clustering': True, 'eps_adjust': 0.2, 'min_samples': 5.0, 'clustered_pct_min': 0.5, 'cluster_span_min': 0.1, 'shift_error': 10, 'max_deviation_sigma': 0.3, 'max_deviation_height': 0.15, 'fit batch': 900, 'ion_types': ('b', 'y'), 'frag_acc': 0.01, 'candidate threshold': 1.5, 'min_spec_matched': 4, 'force_term_loc': False, 'use_all_loc': False, 'variable_mods': 5, 'multiple_mods': True, 'fix_mod_zero_thresh': 3.0, 'min_fix_mod_pep_count_factor': 2.0, 'recommend isotope threshold': 10.0, 'min_loc_count': 10, 'window': 13, 'bins': array([-500.        , -499.999     , -499.998     , ...,  499.99799998,
        499.99899998,  499.99999998]), 'output directory': 'D:\\MSFragger_Temp\\Immunopeptidomics\\CRC_Immunopeptidomics\\MSFragger_OpenSearch_1_Output\\AA_Stat\\Output'})
Traceback (most recent call last):
  File "c:\users\parth\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\parth\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\parth\AppData\Local\Programs\Python\Python39\Scripts\AA_stat.exe\__main__.py", line 7, in <module>
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\AA_stat\main.py", line 43, in main
    AA_stat.AA_stat(params_dict, args)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\AA_stat\AA_stat.py", line 322, in AA_stat
    logger.debug('Fixed modifications: %s', params_dict['fix_mod'])
KeyError: 'fix_mod'

Please do advise me on how to troubleshoot. Thank you.

Regards,
Ben

**Comment by levitsky** [comment]
Hi @BenSamy2020,

There are two issues here. One is the very uninformative error message (I fixed it in the latest commit), the other one is the real problem: AA_stat doesn't find any files in the directory you provided. Are you sure the directory paths are correct and there are pepXML and mzML files in those folders? The command suggests that you have a separate `pepXML` folder and a `mzML` folder inside `MSFragger_OpenSearch_1_Output\AA_Stat`. Can you verify?

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

My apologies, I had been feeding the wrong path to AA_Stat, hence not files were detected. I have successfully ran the command.

Once again, my apologies.

Regards,
Ben
