### ISSUE TITLE
Program Execution Bug

### ISSUE THREAD

**Issue by BenSamy2020** [SimpleNumber/aa_stat#3]
Greetings,

I am a non-programmer. I am trying to use your developed tool to interpret MSFragger OpenSearch results. When I tried using the aa_stat -h command on cmd I am experience an error. The error message is attatched below for your reference. Please do advise me on how I should proceed to successfully use your program. I am sorry if I made any silly mistake with regards to entering the right command to enter the help interface. 

Regards,
Ben

![aa_stat_Error_Message](https://user-images.githubusercontent.com/69944967/113238870-f1b46280-92ec-11eb-8245-7df9cb177e45.JPG)

**Comment by SimpleNumber** [comment]
Hi, Ben!

Thank you for your report. I have fixed the bug. Please update AA_stat and it should start to work.

Regards,
Julia

**Comment by BenSamy2020** [comment]
Greetings,

It working now. Also I forgot to mention the stup.py file has a bug too. Not able to install directly using pip install +git.
I am a full on molecular biologist and not an expert in programming. Based on the error message and googling. I believe the bug is in the setup.py file in on line 9.

It should be "    long_description     = (''.join(open('README.MD'**,encoding="utf-8"**).readlines()))," 

,encoding="utf-8" was missing.

Regards,
Ben

**Comment by levitsky** [comment]
Thank you Ben. We accidentally added some non-ASCII characters to the README file, hence the error. Should be fixed now.
