### ISSUE TITLE
Command to submit a list of --mzml (>50) and --pepXML files (>50)

### ISSUE THREAD

**Issue by BenSamy2020** [SimpleNumber/aa_stat#7]
Greetings,

By any chance is there any command to submit a folder containing a batch of mzml files and another folder containing a batch of corresponding pepXML files?

I have currently 70 mzml and 70 pepXML file to submit for aa_stat analysis.

Regards,
Ben

**Comment by levitsky** [comment]
Hi Ben,

we've looked into it and found out how non-trivial this is on Windows. On Linux, you would just be able to pass `*.pepXML`. On Windows, you can get something close using Powershell, but generally this is very hard. We will update AA_stat by supporting whole directories or globs so that it's easier to use on Windows.

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

I am new to programming field. Currently, getting my hand wet with python on windows. As I start performing more programming work, I am realizing the benefits of linux platform.

Are you going to provide an update that supports whole dir or globs when using with windows soon?

Regards,
Ben

**Comment by levitsky** [comment]
@BenSamy2020 I just pushed a commit which lets you pass directory names instead of files, you can give it a try.

**Comment by BenSamy2020** [comment]
Greeting,

Ok will try it now. I really appreciate your help.

Regards,
Ben

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

I managed to successfully run the program containing the directories for mzml and pepXML files.
Below is the cmd messages for your reference. - Does it look alright?
   
C:\Windows\System32>aa_stat -h
usage: AA_stat [-h] [--params PARAMS] [--dir DIR] [-v {0,1,2,3}]
               [--mgf MGF [MGF ...] | --mzml MZML [MZML ...]]
               (--pepxml PEPXML [PEPXML ...] | --csv CSV [CSV ...])

optional arguments:
  -h, --help            show this help message and exit
  --params PARAMS       CFG file with parameters. If there is no file, AA_stat
                        uses default one. An example can be found at
                        https://github.com/SimpleNumber/aa_stat
  --dir DIR             Directory to store the results. Default value is
                        current directory.
  -v {0,1,2,3}, --verbosity {0,1,2,3}
                        Output verbosity
  --mgf MGF [MGF ...]   MGF files to localize modifications
  --mzml MZML [MZML ...]
                        mzML files to localize modifications
  --pepxml PEPXML [PEPXML ...]
                        List of input files in pepXML format
  --csv CSV [CSV ...]   List of input files in CSV format

C:\Windows\System32>aa_stat --dir D:\AA_Stat_Analysis\aa_stat_output --mzml D:\A
A_Stat_Analysis\Vivax_OpenSearch\mzML_Files --pepxml D:\AA_Stat_Analysis\Vivax_O
penSearch\pepXML_Files
test_theor_spec_PEPTIDE (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_PEPTIDE_cz (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_PEPTIDEterm (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_PEvPTIDE (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_PEvaPTIDE (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_mPEPTIDE (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_termPEPTIDE (AA_stat.tests.AAstatTheorSpectrumTest) ... ok
test_theor_spec_vPEPTIDE (AA_stat.tests.AAstatTheorSpectrumTest) ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.006s

OK
    INFO: [22:31:18] Starting...
    INFO: [22:31:18] Using default parameters for AA_stat.
    INFO: [22:31:19] Using fixed modifications: none.
    INFO: [22:31:19] Variable modifications in search results: none.
    INFO: [22:31:19] Reading input files...
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 106.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 106.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 110.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 108.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 116.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 117.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 114.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 121.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 124.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 115.
Skipping mass calibration: not enough peptides near zero mass shift.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 100.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 156.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 157.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 156.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 101.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 103.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Skipping mass calibration: not enough peptides near zero mass shift.
Not enough data for cluster analysis. Need at least 500 peptides near zero, foun
d 101.
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\matplotlib\collections.py:1039: UserWarning: Collection without array used. Mak
e sure to specify the values to be colormapped via the `c` argument.
  warnings.warn("Collection without array used. Make sure to "
    INFO: [22:33:01] Starting analysis...
    INFO: [22:33:02] Performing Gaussian fit...
    INFO: [22:35:11] Discarding bad peaks...
    INFO: [22:35:11] Joined mass shifts ['-128.0575', '-128.0575']
    INFO: [22:35:11] Joined mass shifts ['-99.0782', '-99.0687']
    INFO: [22:35:11] Joined mass shifts ['-87.0314', '-87.0313']
    INFO: [22:35:11] Joined mass shifts ['-81.1054', '-81.0963']
    INFO: [22:35:11] Joined mass shifts ['-71.0374', '-71.0369']
    INFO: [22:35:11] Joined mass shifts ['-48.0452', '-48.0451']
    INFO: [22:35:11] Joined mass shifts ['-42.0579', '-42.0577']
    INFO: [22:35:11] Joined mass shifts ['-18.0106', '-18.0105']
    INFO: [22:35:11] Joined mass shifts ['0.0003', '0.0004']
    INFO: [22:35:11] Joined mass shifts ['13.9798', '13.9800', '13.9800']
    INFO: [22:35:11] Joined mass shifts ['15.9957', '15.9956']
    INFO: [22:35:11] Joined mass shifts ['27.9954', '27.9953', '27.9951']
    INFO: [22:35:11] Joined mass shifts ['55.9900', '55.9905']
    INFO: [22:35:11] Joined mass shifts ['57.0217', '57.0218']
    INFO: [22:35:11] Joined mass shifts ['85.0171', '85.0172']
    INFO: [22:35:11] Joined mass shifts ['128.0951', '128.0954']
    INFO: [22:35:11] Joined mass shifts ['162.0533', '162.0533', '162.0530']
    INFO: [22:35:11] Joined mass shifts ['190.0477', '190.0482']
    INFO: [22:35:11] Joined mass shifts ['247.0694', '247.0702']
    INFO: [22:35:11] Peaks for subsequent analysis: 372
    INFO: [22:35:11] Performing group-wise FDR filtering...
    INFO: [22:35:19] # of filtered mass shifts = 10
    INFO: [22:35:19] Systematic mass shift equals to +0.0003
    INFO: [22:35:19] Calculating distributions...
    INFO: [22:35:19] Mass shifts:
    INFO: [22:35:19] +0.0000 Da
    INFO: [22:35:19] +1.0028 Da
    INFO: [22:35:19] +27.9949 Da
    INFO: [22:35:19] +57.0215 Da
    INFO: [22:35:19] +58.0072 Da
    INFO: [22:35:19] +58.0234 Da
    INFO: [22:35:20] +85.0169 Da
    INFO: [22:35:20] +114.0429 Da
    INFO: [22:35:20] +162.0528 Da
    INFO: [22:35:20] +171.0643 Da
    INFO: [22:35:20] Summary histogram saved.
    INFO: [22:35:26] Starting Localization using MS/MS spectra...
    INFO: [22:35:26] Reference mass shift +0.0000
    INFO: [22:35:26] Localizing +0.0000...
    INFO: [22:35:26] Localizing +1.0028...
c:\users\parthiban samy\appdata\local\programs\python\python37\lib\site-packages
\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from
ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays
 with different lengths or shapes) is deprecated. If you meant to do this, you m
ust specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
    INFO: [22:35:27] Localizing +27.9949...
    INFO: [22:35:29] Localizing +57.0215...
    INFO: [22:35:33] Localizing +58.0072...
    INFO: [22:35:34] Localizing +58.0234...
    INFO: [22:35:35] Localizing +85.0169...
    INFO: [22:35:37] Localizing +114.0429...
    INFO: [22:35:51] Localizing +162.0528...
    INFO: [22:35:52] Localizing +171.0643...
    INFO: [22:35:56] Plotting mass shift figures...
    INFO: [22:36:08] AA_stat results saved to D:\AA_Stat_Analysis\aa_stat_output

    INFO: [22:36:08] Reference bin is at zero shift.
    INFO: [22:36:08] Recommended fixed modifications: +57.0215 @ C.
    INFO: [22:36:08] Recommending multiple modifications on same residue.
    INFO: [22:36:08] Recommended isotope mass error: 1.
    INFO: [22:36:08] Recommended variable modifications: 1 @ isotope error, +27.
9949 @ N-term, +57.0215 @ N-term, +57.0215 @ K, +162.0528 @ N-term, +114.0429 @
N-term.
    INFO: [22:36:08] Done.

C:\Windows\System32>

**Comment by levitsky** [comment]
Yep, the output seems normal. I will look into suppressing or addressing the unneeded warnings that you see, but don't worry about it

**Comment by BenSamy2020** [comment]
Amazing.

On a side note, are you open to collaboration? Can you provide me your email address?
I will send you an official email to discuss about an idea that I have, that can significantly benefit from this program.

Regards,
Ben

**Comment by levitsky** [comment]
You're welcome to contact me via the email I shared before (lev.levitsky@phystech.edu) or [my PI](https://gorshkovlab.github.io/about/).

**Comment by BenSamy2020** [comment]
Greetings,

Thank you!

Regards,
Ben
