### ISSUE TITLE
Isotope Error recommended variable modification

### ISSUE THREAD

**Issue by BenSamy2020** [SimpleNumber/aa_stat#9]
Greetings @levitsky,

I recently performed aa_stat analysis and for recommended a modification of isotope error. Could you advise me on how to input this modification into my variable modification search setting?

![image](https://user-images.githubusercontent.com/69944967/162549038-6f4b0bde-0579-4227-aab8-7fff217904c6.png)

Regards,
Ben

**Comment by levitsky** [comment]
Hi @BenSamy2020,

Isotope error is a separate parameter: https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#isotope_error

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

By any chance are you able to share some publication on Isotope error. I am having trouble understanding what does isotope error mean.

Regards,
Ben

**Comment by levitsky** [comment]
I'm not sure about the best read about this parameter, although my colleagues have actually written a paper specifically about it: https://pubs.acs.org/doi/abs/10.1021/jasms.0c00281

I don't know if I can explain it better than everything you have already read about it, but isotope error means that the search engine can match a peptide to a spectrum if its mass is off by ~1 Da, allowing for the possibility that the instrument isolated a C13 peak but annotated it as the monoisotopic peak.

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

Thank you for your explanation. The part that I am confused about is, once the mass spec detects the isotopic cluster, it should pick the most abundant peak for fragmentation which is usually the C12. Based on your above explanation, there might be a possibility for the mass spec to pick a C13 peak and send it for fragmentation? (this incorrect picking might be due to reasons explained in your above paper).

Also thanks for sharing the paper. Now I can add another tool into my proteomics toolkit. Currently, testing it out.

Regards,
Ben

**Comment by levitsky** [comment]
Yes @BenSamy2020 , exactly, and this parameter allows to correct this error. In open search, you will see extra "+1" mass shifts if such incorrect assignment happens often: basically, for every abundant +M shift you will see also a smaller +M+1 shift. These are from peptides whose isotope peak was selected wrongly.

AA_stat detects this and marks these peaks as "isotope of +M" in the report. It also recommends isotope error for close search if these "isotope shifts" are abundant.

I'm glad I could help!
